#!/bin/bash
#Telegram & Whatsapp media cleaner.
#Written by Sars.
#
#Fire_it_up!{{{
on_run() {
	if [[ "$1" =~ ^[w|W][a|A] ]]; then
		wa_cl
	elif [[ "$1" =~ ^[t|T][g|G] ]]; then
		tg_cl
	else
		wa_cl
	fi
}
#}}}

#Telegram_cleaner{{{
tg_cl() {
local trash
local tg_dir="$HOME/storage/shared/Telegram"
	for trash in "${sub_dirs[@]}"; do
		rm -rf "$fls"/*
	done
echo "Telegram dir. cleaned!"
}
#}}}

#Whatsapp_cleaner{{{
wa_cl() {
local trash
local wa_dir="$HOME/storage/shared/WhatsApp/Media"
	for trash in "${sub_dirs[@]}"; do
		rm -rf "$fls"/*
	done
echo "WhatsApp dir. cleaned!"
}	
#}}}

on_run "$@"