#! /bin/bash
#Script for Backing-Up and restoring Termux environment.
#Written by Sars!
#0.9

#GLOBAL_VARS
fbup="../"
hbup="../etc ../home"
dbpt="$HOME/storage/shared/TermuxBackups/"
chc="Backup Restore List-all Remove Quit"
PS3="> "

#Wrapper()
lst() { ls -lh "$1"; } 2>/dev/null
rmr() { rm -r "$1" "$2"; } 2>/dev/null
mkd() { mkdir "$1" "$2"; } 2>/dev/null
mov() { mv "$1" "$2"; } 2>/dev/null

#Create_directory
[[ ! -d "$dbpt" ]] && mkd -p "$dbpt"

#Show the menu
#Allow the functions to be called defined below. Hackish way, thanks stackoverflow :P
show_menu() {
	select opt in ${chc[@]}; do
	echo $opt
	break
	done
}

#Check if file exists.
chk_file() {
 	if [[ ! -z "$1" && -f "$1" ]]; then
 		return
 	else
 		echo -e "\n$flnm File not found!"; exit 1;
	fi
}

#Function for removing files.
rm_file() {
	cd "$1"
	echo "Here is a list of all your Backups:"
	lst "$1"; echo
	read -p "Enter Filename: " flnm
	chk_file "$flnm"
	read -p "Are you sure you want to remove $flnm?[y/n]: " ans

	if [[ ! -z "$ans" && "$ans" =~ ^[Y|y] ]]; then
		rmr "$flnm"
		echo -e "\nRemoved!"
	else
		echo -e "\nAborting.."; show_menu;
	fi		
}

#Choose Backup-Type.
bup_type() {
	echo "Full Backup: Backs-Up Both entire root directory"
	echo "Half Backup: Backs-Up /usr/etc & /home only."
	read -p "Full or Half: " ans

	if [[ ! -z "$ans" && "$ans" =~ ^[F|f]ull ]]; then
		echo "Initiating Full Backup..."; echo
		tar_bup "$fbup" "root_$(date --i)" "$dbpt"

	elif [[ ! -z "$ans" && "$ans" =~ ^[H|h]alf ]]; then
		echo "Initiating Half Backup..."; echo
		tar_bup "$hbup" "usr_$(date --i)" "$dbpt"

	else
			show_menu
	fi
}

#Function for Backing-Up.
tar_bup() {
	tar -czpf "$2" $1 2>/dev/null
	mov "$2" "$3"
	echo -e "Configs Backed-Up at \n$3"
}

#Fix tar cannot create symlink error, cause android's storage filesystem format doesnt support moving/copying symlinks
fix_rest() {
	cd "$1"
	cp "$2" "$HOME" 
	cd "$HOME"
} 2>/dev/null

#Funtcion for Restoring.
tar_rest() {
	echo "Here is the list of all your Backups:"
	lst "$1"
	read -p "Enter File Name: " flnm
	fix_rest "$1" "$flnm"
	chk_file "$flnm"
	tar -xzpf "$flnm" -C ../ 2>/dev/null
	rm "$flnm"
}

#Iterate over the menu everytime
while true; do
COLUMNS=5
opt=$(show_menu)

case $opt in
	"Quit")
		break
		;;

	"Backup")
		bup_type
 		echo
 		;;

	"Restore")
		tar_rest "$dbpt"
		echo -e "\nConfigs Restored!"
		echo
        ;;
            
	"List-all")
		echo "Here is the list of all your Backups:"
		lst "$dbpt"
		echo
		;;

	"Remove")
		rm_file "$dbpt"
		echo
		;;
            
	*) 
		echo "Invalid Option"
		echo
		;;
	esac
done